######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 30 11:22:12 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../common ../reactor

# Input
HEADERS += Thread.hpp
SOURCES += Main.cpp Thread.cpp ../common/Daemon.cpp ../reactor/Exception.cpp
