######################################################################
# Automatically generated by qmake (2.01a) Wed Oct 12 17:35:39 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . 
INCLUDEPATH += .
LIBS += 

# Input
HEADERS += CircleBuf.hpp
SOURCES += main.cpp CircleBuf.cpp
CONFIG -= qt
CONFIG += debug
