######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 15 16:45:31 2012
######################################################################

TEMPLATE = app
TARGET = Dispacth
DEPENDPATH += .
INCLUDEPATH += .
OBJECTS_DIR = .obj

INCLUDEPATH += . ../reactor/ ../network/ ../common/ ../protocol/ ../dispatch ../threadpool ../active ../circle /usr/local/include ../service ../utils ../group ../server ../mysql

LIBS += -L/usr/local/lib -lpthread -lprotobuf -lmysqlcppconn

# Input
HEADERS += DispatchCenter.hpp

SOURCES += ../group/Registry.cpp \
../common/Conf.cpp \
../common/Daemon.cpp \
../service/FightingService.cpp \
../service/FightRequestService.cpp \
../service/FightResponseService.cpp \
../service/FightResultService.cpp \
../service/PKListService.cpp \
../service/PropertyService.cpp \
../service/VersionService.cpp\
../protocol/FightClub.pb.cc \
../mysql/MySQL.cpp \
../mysql/PropertyImpl.cpp \
DispatchCenter.cpp \
Main.cpp
