######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 8 20:39:28 2013
######################################################################

TEMPLATE = app
TARGET =  Player
OBJECTS_DIR = .obj
DEPENDPATH += .
QMAKE_CXXFLAGS += -std=gnu++0x
INCLUDEPATH += . ../common/  ../threadpool ../active ../circle /usr/local/include ../service ../utils ../group ../server ../mysql ../string

LIBS += -L/usr/local/lib/ -lprotobuf -lpthread  -lmysqlcppconn -lboost_system -lboost_thread

# Input
HEADERS += Player.hpp PlayerCache.hpp
SOURCES += Main.cpp Player.cpp PlayerCache.cpp ../common/Daemon.cpp ../string/String.cpp ../string/Element.pb.cc ../utils/StringTool.cpp ../mysql/MyPool.cpp ../mysql/MySQL.cpp ../mysql/SQLDef.cpp ../mysql/SQLImpl.cpp ../common/Conf.cpp

CONFIG += debug
CONFIG -= qt
