######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 30 12:06:16 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../
LIBS += -lsqlite3

# Input
HEADERS += ../sqlite3.hpp
SOURCES += ../sqlite3.cpp main.cpp

CONFIG -= qt
CONFIG += debug
