######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 6 23:02:59 2012
######################################################################

OBJECTS_DIR=.obj
TEMPLATE = app

TARGET = MySQL

DEPENDPATH += . 

INCLUDEPATH += . ../common ../reactor ../active ../protocol ../utils/

LIBS += -L /usr/local/lib/ -lmysqlcppconn -lprotobuf -lboost_system -lboost_thread

# Input
HEADERS += MySQL.hpp
SOURCES += Main.cpp MySQL.cpp ../common/Conf.cpp ../common/Daemon.cpp AsyncMySQL.cpp ../reactor/Exception.cpp ../protocol/FightClub.pb.cc ConstSQL.cpp DBImpl.cpp MyPool.cpp

# Config
CONFIG -= qt
CONFIG += debug
