######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 7 10:57:36 2013
######################################################################

TEMPLATE = app
TARGET = String
DEPENDPATH += .
QMAKE_CXXFLAGS += -std=gnu++0x
INCLUDEPATH += . ../common ../utils
LIBS += -lprotobuf -lpthread

# Input
HEADERS += Element.pb.h String.hpp
SOURCES += Element.pb.cc String.cpp Main.cpp ../common/Daemon.cpp ../common/PidSet.cpp ../common/SigChld.cpp ../utils/StringTool.cpp

CONFIG += debug
CONFIG -= qt
